#!/usr/bin/env Rscript

sys = modules::import('sys')

sys$run({
    input = sys$args[1]
    output = sys$args[2]
    extra = parse(text = sprintf('{%s}', sys$args[-c(1, 2)]))

    message('Environment: ', extra)
    env = new.env(parent = parent.env(globalenv()))
    eval(extra, envir = env)

    library(brew)
    result = brew(input, output, envir = env)
    if (inherits(result, 'try-error'))
        1
})

# vim: ft=r
