#!/usr/bin/env Rscript

library(modules, warn.conflicts = FALSE, quietly = TRUE)
sys = import('sys')

sys$run({
    args = sys$cmdline$parse(opt('a', 'alpha', 'significance threshold for enrichment', 0.001),
                             arg('species', 'the species'),
                             arg('type', 'the type (“mrna” or “trna”)',
                                 validate = function(x)  x %in% c('mrna', 'trna')),
                             arg('outfile', 'the output filename'))

    base = import('ebits/base')
    data = import('../data')
    config = import(paste('../config', args$species, sep = '_'))
    load_data = function (type)
        data[[paste(args$type, type, sep = '_')]](config)

    counts = load_data('counts')
    design = load_data('design')

    de = import('./de')
    de_genes = de$de_genes(counts, design, config$contrasts, args$alpha)
    saveRDS(de_genes, args$outfile)
})

# vim: ft=r
