#!/usr/bin/env Rscript

library(modules, warn.conflicts = FALSE, quietly = TRUE)
sys = import('sys')

sys$run({
    args = sys$cmdline$parse(arg('species', 'the species'))

    full_species = switch(args$species,
                          human = 'Homo sapiens',
                          mouse = 'Mus musculus',
                          stop('Invalid species name provided'))

    query_url = sprintf('http://ribosome.med.miyazaki-u.ac.jp/rpg.cgi?mode=orglist&org=%s',
                        URLencode(full_species))

    import_package('rvest', attach = TRUE)
    xml2 = import_package('xml2')
    html = xml2$read_html(query_url)
    genes = html %>%
        html_nodes('table td[class!=header]') %>%
        html_text() %>%
        grep(pattern = '^\\s*$', invert = TRUE, value = TRUE)

    writeLines(genes, stdout())
    invisible(NULL)
})

# vim: ft=r
