#!/usr/bin/env Rscript

library(modules, warn.conflicts = FALSE, quietly = TRUE)
sys = import('sys')

plot_te = function (data, summary) {
    import_package('ggplot2', attach = TRUE)

    plot = ggplot(data, aes(x = Mode, y = TE)) +
        geom_boxplot(width = if (summary) 0.4 else 0.2, outlier.size = 0) +
        scale_y_continuous(limits = c(0.45, 0.85)) +
        facet_wrap(~ Which, nrow = 1) +
        theme_bw()

    if (summary)
        plot
    else {
        import_package('ggbeeswarm', attach = TRUE)
        plot +
            geom_point(aes(color = mRNA, shape = tRNA),
                       position = position_beeswarm()) +
            scale_color_manual(limits = names(config$celltype_colors),
                               values = config$celltype_colors) +
            scale_shape_manual(limits = names(config$celltype_colors),
                               values = c(15, 4, 5, 16))
    }
}

mean_center = function (all_te) {
    import_package('dplyr', attach = TRUE)
    trna_zscores = all_te %>%
        filter(Mode == 'Match') %>%
        group_by(Which) %>%
        mutate(AllMedian = median(TE)) %>%
        group_by(tRNA, add = TRUE) %>%
        mutate(tRNAMedian = median(TE)) %>%
        summarize(Scaling = first(tRNAMedian / AllMedian))

    inner_join(all_te, trna_zscores, by = c('Which', 'tRNA')) %>%
        mutate(TE = TE / Scaling)
}

sys$run({
    args = sys$cmdline$parse(opt('c', 'mean-center', 'center tRNA strata before plotting?', FALSE),
                             opt('s', 'summary', 'plot summary rather than detailed points?', TRUE),
                             arg('species', 'the species'),
                             arg('outfile', 'the filename of the PDF output'))

    config = import(sprintf('../config_%s', args$species))
    te = readRDS(sprintf('results/te-%s.rds', args$species))
    if (args$`mean-center`)
        te = mean_center(te)

    # Required by ggplot2, see <https://github.com/hadley/ggplot2/issues/1384>
    library(methods)
    on.exit(dev.off())
    pdf(args$outfile)
    plot(plot_te(te, args$summary))
    NULL
})

# vim: ft=r
