#!/usr/bin/env Rscript

library(modules, warn.conflicts = FALSE, quietly = TRUE)
sys = import('sys')

sys$run({
    args = sys$cmdline$parse(arg('species', 'the species'),
                             arg('outfile', 'the filename of the PDF output'))

    import_package('dplyr', attach = TRUE)
    import_package('tidyr', attach = TRUE)

    data = import('../data')
    config = import(sprintf('../config_%s', args$species))
    trna_modifier_genes = data$trna_modifier_genes(config)

    design = data$mrna_design(config)
    gene_counts = data$mrna_sf_counts(config) %>%
        filter(Gene %in% trna_modifier_genes) %>%
        # Summarize replicates for each celltype
        gather(DO, Count, starts_with('do')) %>%
        inner_join(design, by = 'DO') %>%
        group_by(Gene, Name, Celltype) %>%
        summarize(Count = mean(Count)) %>%
        # Rowwise scaling
        group_by(Gene) %>%
        mutate(`Scaled count` = as.numeric(scale(Count))) %>%
        ungroup()

    import_package('ggplot2', attach = TRUE)

    ggplot(gene_counts) +
        aes(relevel(factor(Celltype), 'Liver-Adult'), Name) +
        geom_tile(aes(fill = `Scaled count`)) +
        scale_x_discrete('Celltype', expand = c(0, 0)) +
        scale_y_discrete(expand = c(0, 0)) +
        scale_fill_gradient2(low = 'blue', mid = 'white', high = 'red') +
        guides(fill = FALSE) +
        theme(axis.ticks = element_blank(),
              panel.background = element_rect(fill = 'transparent'))
})

# vim: ft=r
