#!/usr/bin/env Rscript

library(modules, warn.conflicts = FALSE, quietly = TRUE)
sys = import('sys')

sys$run({
    args = sys$cmdline$parse(arg('species', 'the species'),
                             arg('outfile', 'the filename of the output table'))

    import_package('dplyr', attach = TRUE)
    io = import('ebits/io')

    te = readRDS(sprintf('results/te-%s.rds', args$species))
    contrasts = c('Mismatching', 'DE', 'Enriched GO')

    test = function (alternative)
        function (x)
            wilcox.test(filter(te, Type == 'Matching')$TE,
                        filter(te, Type == x)$TE,
                        alternative = alternative)$p.value

    results = data.frame(Test = sapply(contrasts, test('less')),
                         Inverse = sapply(contrasts, test('greater'))) %>%
        sapply(p.adjust, method = 'bonferroni') %>%
        {cbind.data.frame(Contrast = contrasts, .)}

    io$write_table(results, args$outfile)
})

# vim: ft=r
