#!/usr/bin/env Rscript

library(modules, warn.conflicts = FALSE, quietly = TRUE)
sys = import('sys')

sys$run({
    args = sys$cmdline$parse(arg('species', 'the species'),
                             arg('outfile', 'the filename of the output table'))

    import_package('dplyr', attach = TRUE)
    io = import('ebits/io')
    import('ebits/base')

    te = readRDS(sprintf('results/te-%s.rds', args$species))
    contrasts = rbind(cbind('Matching', c('Mismatching', 'DE', 'Enriched GO')),
                      cbind(c('Simulated DE', 'Simulated GO'),
                            c('DE', 'Enriched GO'))) %>%
        t() %>% as.data.frame(stringsAsFactors = FALSE)

    test = function (contrast)
        wilcox.test(filter(te, Type == contrast[1])$TE,
                    filter(te, Type == contrast[2])$TE,
                    alternative = 'less')$p.value

    results = data.frame(p = sapply(contrasts, test)) %>%
        sapply(p.adjust, method = 'bonferroni') %>%
        {cbind.data.frame(Contrast = sapply(contrasts, c -> sprintf('%s-%s', c[1], c[2])), .)}

    io$write_table(results, args$outfile)
})

# vim: ft=r
